apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /mnt/persistente-vol/wordpress
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
