apiVersion: v1
kind: Service
metadata:
  labels:
    svc: wordpres-svc
  name: wordpress-svc
  namespace: olv
spec:
  ports:
    - name: wordpress-port-svc
      nodePort: 30084
      port: 8084
      protocol: TCP
      targetPort: 80
  selector:
    pod: wordpress-pod
  type: NodePort