apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: wordpress-pvc
  name: wordpress-pvc
  namespace: olv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: wordpress-pv
